homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/Stockholm
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - fd00::/8
        - ::1
#        - 10.5.50.0/24

  customize: !include_dir_merge_named customize
  customize_glob: !include_dir_merge_named customize_glob
  packages: !include_dir_named packages


#lovelace:
#  mode: yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

system_health:

panel_iframe:
  grafana:
    title: "Grafana"
    url: !secret grafana_url
    icon: mdi:graphql

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
  tags_attributes:
    - grafana_name
    - friendly_name

alexa:

google_assistant:
  project_id: !secret ga_project_id
  api_key: !secret ga_api_key
  secure_devices_pin: !secret verisure_default_code
  exposed_domains:
    - switch
    - light
    - group
    - lock
  entity_config:
    group.all_automations:
      expose: false
    switch.telldus_tzwp_102_plug_in_switch_switch:
      expose: false


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.5.50.250
  base_url: !secret base_url

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

speedtestdotnet:
  server_id: 21028
  scan_interval:
    minutes: 180
  monitored_conditions:
    - ping
    - download
    - upload

googlehome:
  devices:
    - host: !secret googlehome1
    - host: !secret googlehome2

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: true
    detection_time: 180
    track_new_devices: false
    monitored_conditions: 
      - ip
      - last_seen
      - latest_assoc_time
      - name
      - powersave_enabled
      - signal
      - tx_power
      - uptime
      - user_id

  - platform: bluetooth_tracker
    request_rssi: true

  - platform: google_maps
    username: !secret maps_user
    password: !secret maps_pass
    max_gps_accuracy: 200

    #  - platform: bluetooth_le_tracker

person:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# media players
media_player: !include media_player.yaml

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_merge_list sensors/

# Zones
zone: !include zones.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# verisure
verisure:
  username: !secret verisure_user
  password: !secret verisure_pass
  default_lock_code: !secret verisure_default_code
  alarm: false
  hygrometers: false
  smartplugs: false
  thermometers: false
  mouse: false
  door_window: false
  locks: true

zoneminder:
  - host: !secret zm_host
    ssl: true
    verify_ssl: true
    path_zms: '/cgi-bin/nph-zms'
    username: !secret zm_user
    password: !secret zm_pass
    #host: 10.5.50.84:81
    #path_zms: /cgi-bin/nph-zms

camera:
  - platform: zoneminder

#tibber:
#  access_token: !secret tibber_token

# Cloud
cloud:

tellduslive:
  #host: 10.5.50.67
  scan_interval: 5

# disabled until summer  
#automower:
#  username: !secret am_user
#  password: !secret am_pass

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

logger:
  default: info
  logs:
    homeassistant.components.zoneminder: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.sensor: warn
    homeassistant.components.sensor.scrape: info
    homeassistant.component.media_player.denonavr: info
    homeassistant.components.unifi: error
    homeassistant.components.shell_command: debug

recorder:
  purge_keep_days: 1
  purge_interval: 1
  include:
    domains:
      - switch
      - media_player
      - sensor
      - device_tracker
  exclude:
    entities:
      - sensor.real_time_consumption_johannedalsvagen_75_b
      - sensor.rtc_accumulated_consumption
      - sensor.rtc_avgpower
      - sensor.rtc_maxpower
      - sensor.rtc_minpower
      - sensor.rtc_current_phase1
      - sensor.rtc_current_phase2
      - sensor.rtc_current_phase3
      - sensor.rtc_power_phase1
      - sensor.rtc_power_phase2
      - sensor.rtc_power_phase3
      - sensor.rtc_voltage
      - sensor.hourly_energy
      - sensor.dayly_energy
      - sensor.weekly_energy
      - sensor.monthly_energy
      - sensor.yearly_energy


group: !include_dir_merge_named groups/
light: !include light.yaml
binary_sensor: !include binary_sensors.yaml
utility_meter: !include utility_meter.yaml


input_boolean: !include input/boolean.yaml
#input_select: !include input/select.yaml
input_number: !include input/number.yaml
#input_datetime: !include input/datetime.yaml
#input_text: !include input/text.yaml

automation: !include_dir_merge_list automations/
script: !include scripts.yaml

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py > /config/lovelace-gen.log'
  remove_google_cookie: 'rm /config/.google_maps_location_sharing.cookies.*'
