homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - fd00::/8
        - ::1
        - 172.30.32.2
        - 10.5.50.149
#        - 10.5.50.0/24

  customize: !include_dir_merge_named customize
  customize_glob: !include_dir_merge_named customize_glob
  packages: !include_dir_named packages


  # Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

system_health:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - vacuum
  exclude:
    entities:
      - sensor.real_time_consumption_johannedalsvagen_75_b
      - sensor.hourly_energy
      - sensor.dayly_energy
      - sensor.weekly_energy
      - sensor.monthly_energy
      - sensor.yearly_energy
      - sensor.time
      - sensor.time_2
      - sensor.time_3
      - sensor.heater_departuretime
      - sensor.heater_activationtime
      - sensor.heater_temptime
      - sensor.heater_forecast
      - sensor.rtc_power_1min
      - sensor.rtc_accumulated_consumption_1min
      - sensor.rtc_avgpower_1min
      - sensor.rtc_maxpower_1min
      - sensor.rtc_minpower_1min
      - sensor.rtc_current_phase1_1min
      - sensor.rtc_current_phase2_1min
      - sensor.rtc_current_phase3_1min
      - sensor.rtc_accumulated_consumption_state
      - sensor.rtc_avgpower_state
      - sensor.rtc_maxpower_state
      - sensor.rtc_minpower_state
      - sensor.rtc_current_phase1_state
      - sensor.rtc_current_phase2_state
      - sensor.rtc_current_phase3_state
  tags_attributes:
    - grafana_name
    - friendly_name

alexa:

google_assistant:
  project_id: !secret ga_project_id
  #api_key: !secret ga_api_key
  service_account: !include ga_homeassistant.json
  secure_devices_pin: !secret verisure_default_code
  report_state: true
  exposed_domains:
    - switch
    - light
    - group
    - lock
    - sensor
  entity_config:
    group.all_automations:
      expose: false
    switch.sp120_1:
      expose: false
    sensor.outdoor_temperatures:
      expose: false
    # light.kitchentable:
    #   name: 'Kitchen table'
    #   aliases:
    #     - 'table light'
    #     - 'kökslampa'
    #     - 'kökslampan'
    #     - 'kökslyset'
    # switch.switch_tiny_1:
    #   name: 'Kitchen window'
    #   aliases:
    #     - 'kitchen window light'
    #     - 'köksfönsterlampan'
    # light.bedroom_ceiling:
    #   name: 'Bedroom ceiling'
    #   aliases:
    #     - 'Sovrumslampan'
    #     - 'Sovrumstaklampan'


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.5.50.250
  #base_url: !secret base_url

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

mobile_app:

speedtestdotnet:
  server_id: 6061
#  scan_interval:
#    minutes: 180
  manual: true
  monitored_conditions:
    - ping
    - download
    - upload

#googlehome:
#  devices:
#    - host: !secret googlehome1
#    - host: !secret googlehome2

device_tracker:
#  - platform: bluetooth_tracker
#    request_rssi: true

#   - platform: google_maps
#     track_new_devices: true
#     username: !secret maps_user
# #    password: !secret maps_pass
#     max_gps_accuracy: 200
#     scan_interval: 60

    #  - platform: bluetooth_le_tracker

person:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

mqtt:

# APC UPS
apcupsd:
  host: a722577e-apcupsd
  
# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# stream
stream:

# media source
media_source:

# zeroconf
zeroconf:
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    base_url: !secret base_url
    
# verisure
# verisure:
#   username: !secret verisure_user
#   password: !secret verisure_pass
#   default_lock_code: !secret verisure_default_code
#   alarm: false
#   hygrometers: false
#   smartplugs: false
#   thermometers: false
#   mouse: false
#   door_window: false
#   locks: true


tibber:
  access_token: !secret tibber_token

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Cloud
cloud:

# vacuum cleaners
vacuum:
  - platform: xiaomi_miio
    name: 'Vac-It Ralph'
    host: !secret roborock_s5max_host
    token: !secret roborock_s5max_token

# HACS
hacs:
  token: !secret hacs_token
#  theme: true

# HACS integrations
# -----------------
svt_play:

tv4_play:

# HQ automower
automower:
  username: !secret am_user
  password: !secret am_pass

# sure catflap
surepetcare:
  username: !secret sure_petflap_username
  password: !secret sure_petflap_password
  #household_id: !secret sure_petflap_household_id
  # flaps: !secret sure_petflap_flaps
  # pets: !secret sure_petflap_pets

# midea cloud
climate:
  - platform: midea_ac
    host: !secret midea_host
    id: !secret midea_id


telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_apikey
    allowed_chat_ids:
      - !secret telegram_bot_id_group
      - !secret telegram_bot_id_linus

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_key
    
  - platform: html5
    name: google
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

  - platform: telegram
    name: castle
    chat_id: !secret telegram_bot_id_group

  - platform: group
    name: ALL_DEVICES
    services:
      - service: mobile_app_oneplus_8t
      - service: mobile_app_isabells_iphone

logger:
  default: warn
  logs:
    # temp debug for unifi
    # aiounifi: debug
    # homeassistant.components.unifi: debug
    # homeassistant.components.device_tracker.unifi: debug
    # homeassistant.components.switch.unifi: debug
    homeassistant.components.device_tracker: warn
    homeassistant.components.sensor: warn
    homeassistant.components.sensor.scrape: info
    homeassistant.component.media_player.denonavr: info
    homeassistant.components.shell_command: warn
    homeassistant.helpers.script: warn
    homeassistant.components.automation: warn
    homeassistant.components.websocket_api.http.connection: warn
    custom_components.nordpool: warn
    # custom_components.husqvarna_automower: debug
    # custom_components.husqvarna_automower.vacuum: debug
    # custom_components.husqvarna_automower.config_flow: debug
    # aioautomower: debug

recorder:
  db_url: !secret mariadb
  purge_keep_days: 2
  auto_purge: true
  include:
    domains:
      - switch
      - media_player
      - sensor
      - person
      - vacuum
      - device_tracker
      - binary_sensor
      - input_boolean
      - light
      - counter
      - lock
      - vacuum
  exclude:
    event_types:
      # - state_changed # this is history stats
      - call_service
    entities:
      - sensor.real_time_consumption_johannedalsvagen_75_b
      - sensor.outdoor_temperatures
      - sensor.hourly_energy
      - sensor.dayly_energy
      - sensor.weekly_energy
      - sensor.monthly_energy
      - sensor.yearly_energy
      - sensor.time
      - sensor.time_2
      - sensor.time_3
      - sensor.heater_departuretime
      - sensor.heater_activationtime
      - sensor.heater_temptime
      - sensor.heater_forecast
      # - sensor.rtc_power_1min
      # - sensor.rtc_accumulated_consumption_1min
      # - sensor.rtc_avgpower_1min
      # - sensor.rtc_current_phase1_1min
      # - sensor.rtc_current_phase2_1min
      # - sensor.rtc_current_phase3_1min
      # - sensor.rtc_accumulated_consumption_state
      # - sensor.rtc_avgpower_state
      # - sensor.rtc_maxpower_state
      # - sensor.rtc_minpower_state
      # - sensor.rtc_current_phase1_state
      # - sensor.rtc_current_phase2_state
      # - sensor.rtc_current_phase3_state
      - sensor.ups_status_date
      - sensor.ups_status_data
    entity_globs:
      # power cunsumption
      - sensor.rtc_*_1min
      - sensor.rtc_*_state
      # frigate
      - sensor.*_process_fps
      - sensor.*_camera_fps
      - sensor.*_detection_fps


# media players
media_player: !include media_player.yaml

image_processing: !include image_processing.yaml

# include sensors
sensor: !include_dir_merge_list sensors/

# Cameras
camera: !include cameras.yaml

# Switches
switch: !include switch.yaml

group: !include_dir_merge_named groups/
light: !include_dir_merge_list lights/
#light: !include light.yaml
#binary_sensor: !include binary_sensors.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
utility_meter: !include utility_meter.yaml


input_boolean: !include input/boolean.yaml
#input_select: !include input/select.yaml
input_number: !include input/number.yaml
#input_datetime: !include input/datetime.yaml
#input_text: !include input/text.yaml

automation: !include_dir_merge_list automations/
script: !include scripts.yaml

shell_command:
  #lovelace_gen: 'python /config/lovelace-gen.py > /config/lovelace-gen.log'
