homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/Stockholm

  #customize: !include customize.yaml
  customize: !include_dir_merge_named customize
  customize_glob: !include_dir_merge_named customize_glob

# Enables the frontend
frontend:

# Enables configuration UI
config:

#panel_iframe:
#  nodered:
#    title: 'Node-RED'
#    url: 'http://10.5.50.100:1880'
#    icon: mdi:auto-fix
#  router:
#    title: 'Microtik'
#    url: 'http://10.5.50.1:81'

alexa:

google_assistant:
  project_id: !secret ga_project_id
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - light
    - group

http:
  api_password: !secret http_password
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.5.50.0/24
    - fd00::/8
  base_url: !secret base_url

  #use_x_forwarded_for: true
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

device_tracker:
  - platform: unifi
    host: 10.5.50.91
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: false
    detection_time: 180
    track_new_devices: false
    monitored_conditions: 
      - ip
      - last_seen
      - latest_assoc_time
      - name
      - powersave_enabled
      - signal
      - tx_power
      - uptime
      - user_id

  - platform: bluetooth_tracker
    request_rssi: true

  - platform: google_maps
    username: !secret maps_user
    password: !secret maps_pass
    max_gps_accuracy: 200

    #  - platform: bluetooth_le_tracker

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# media players
media_player: !include media_player.yaml

# trådfri
tradfri:
  host: 10.5.50.72
  allow_tradfri_groups: false

# Track the sun
sun:

# Weather prediction
#sensor: !include sensors.yaml
sensor: !include_dir_merge_list sensors/

# Zones
zone: !include zones.yaml

# Text to speech
tts:
  - platform: google

# verisure
verisure:
  username: !secret verisure_user
  password: !secret verisure_pass
  alarm: 0
  hygrometers: 0
  smartplugs: 0
  thermometers: 0
  mouse: 0
  door_window: 0

zoneminder:
  host: !secret zm_host
  ssl: true
  path_zms: '/cgi-bin/nph-zms'
  #host: 10.5.50.84:81
  #path_zms: /cgi-bin/nph-zms

camera:
  - platform: zoneminder

# Cloud
cloud:

tellduslive:
  update_interval: 5

# disabled until summer  
#automower:
#  username: !secret am_user
#  password: !secret am_pass

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

logger:
  default: warn
  logs:
    homeassistant.components.zoneminder: debug
    homeassistant.components.device_tracker: warn
    homeassistant.components.sensor: warn
    homeassistant.components.sensor.scrape: info
    homeassistant.component.media_player.denonavr: info
    homeassistant.components.unifi: error

recorder:
  purge_keep_days: 5
  purge_interval: 1
  #purge_days: 2
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.time
      - sensor.time_2
      - sensor.heater_hour
      - sensor.heater_minute

group: !include_dir_merge_named groups/
light: !include light.yaml
binary_sensor: !include binary_sensors.yaml

input_boolean: !include input/boolean.yaml
#input_select: !include input/select.yaml
input_number: !include input/number.yaml
#input_datetime: !include input/datetime.yaml
#input_text: !include input/text.yaml

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
