- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: !secret deepstack_port
  #api_key: !secret deepstack_apikey
  timeout: 5
  detect_only: false
  save_file_folder: /media/deepstack/snapshots/
  save_timestamped_file: True
  save_faces: True
  save_faces_folder: /media/deepstack/faces/
  show_boxes: true
  source:
    - entity_id: camera.frontporch_person
      name: frontporch_face