- platform: template
  lights:
    kitchen_north:
      friendly_name: 'Kitchen window light north 1'
      value_template: "{{ is_state('switch.switch_tiny_1', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.switch_tiny_1
      turn_off:
        service: switch.turn_off
        entity_id: switch.switch_tiny_1
