automation:
  view: yes
  entities:
    - group.all_automations

sensors:
  view: yes
  entities:
    - sensor.all_sensors

outdoor_lights:
  name: Outdoor lights
  entities:
    - switch.apple_tree_light
    - switch.switch_garage

window_lights:
  name: Window lights
  entities:
    - switch.proove_1
    - switch.proove_2
    - switch.switch_livingroom_upstairs
    - switch.switch_bedroom
    - switch.switch_workout
    - switch.switch_tiny_1

flvp_sensors:
  name: FLVP Sensors
  entities:
    - sensor.radiator_fram_temperature
    - sensor.radiator_ret_temperature
    - sensor.tilluft_temperature
    - sensor.uteluft_temperature
    - sensor.franluft_temperature
    - sensor.avluft_temperature

linus_trackers:
  name: Linus
  icon: mdi:account
  entities:
    - device_tracker.google_maps_103350380655483099475
      #- device_tracker.android65f131c1941f6a44
    - device_tracker.a83e0e0a0bc4
    - device_tracker.nokia_7_plus

people:
  name: Friends and family
  entities:
    - device_tracker.android7d40d5e0a59e5164
    - device_tracker.galaxys8
    - device_tracker.jiphone
    - device_tracker.8cebc669649e
    - device_tracker.samsunggalaxys7
    - device_tracker.galaxyj5
    - device_tracker.galaxys9
    - device_tracker.88e9fea612d8
    - device_tracker.galaxys6
    - device_tracker.huawei_p20_lite552c717f5

bedroom:
  name: Master bedroom
  entities:
    - switch.switch_bedroom
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity
    - light.bedroom_ceiling

livingroom_downstairs:
  name: Living room downstairs
  entities:
    - sensor.livingroom_downstairs_temperature
    - sensor.livingroom_downstairs_humidity
    - light.10w_driver_1

livingroom_upstairs:
  name: Living room upstairs
  entities:
    - switch.switch_livingroom_upstairs
    - switch.proove_2
    - sensor.livingroom_upstairs_temperature

garage:
  name: Garage
  entities:
    - switch.switch_garage
    - sensor.garage_temperature
    - sensor.garage_humidity
    - sensor.garage_door_state
    - sensor.garage_port_state
    - switch.switch_engine_heater

guestroom:
  name: Guest room
  entities:
    - switch.switch_guestroom
    - sensor.guestroom_temperature
    - sensor.guestroom_humidity

kitchen:
  name: Kitchen
  entities:
    - sensor.kitchen_temperature
    - sensor.kitchen_humidity
    - switch.switch_tiny_1
    - sensor.refriguator_upper_door_state
    - sensor.refriguator_lower_door_state

hobbyroom:
  name: Hobby room
  entities:
    - sensor.hobbyroom_temperature
    - sensor.hobbyroom_humidity

closet:
  name: Closet upstairs
  entities:
    - sensor.closet_temperature
    - sensor.closet_humidity

workoutroom:
  name: Workout room
  entities:
    - switch.switch_workout

roof:
  name: Roof
  entities:
    - sensor.north_roof_temperature
    - sensor.north_roof_humidity
    - sensor.south_roof_temperature
    - sensor.south_roof_humidity

verisure:
  name: Verisure
  entities:
    - lock.ytterdorr

remotes:
  name: Remotes
  entities:
    - switch.remote_1
    - switch.remote_1_a
    - switch.remote_1_b
    - switch.remote_1_c
    - switch.remote_1_alloff

rooms:
  view: yes
  entities:
    - group.bedroom
    - group.livingroom_downstairs
    - group.livingroom_upstairs
    - group.garage
    - group.guestroom
    - group.kitchen
    - group.hobbyroom
    - group.closet
    - group.workoutroom

house:
  view: yes
  entities:
    - group.flvp_sensors
    - group.roof
    - group.garage
    - group.verisure

