#- platform: rest
#  name: Current HA version
#  json_attributes:
#    - created_at
#    - published_at
#  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
#  value_template: '{{ value_json.tag_name }}'
#  scan_interval: 900
#  headers:
#    Accept: application/vnd.github.v3+json
#    Content-Type: application/json
#    User-Agent: Home Assistant REST sensor


- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: Current HA version
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 300