- platform: template
  sensors:
    rtc_voltage:
      friendly_name: Real time consumtion voltage
      unit_of_measurement: V
      value_template: >-
        {% set v = states.sensor.telldus_tzwp_102_plug_in_switch_voltage.state %}
        {% if v|round(0)|string|length != 3 %} {% set v = 230 %} {% endif %}
        {{ v }}

    rtc_current_phase1:
      friendly_name: Real time consumtion phase 1
      unit_of_measurement: A
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase1") }}'    
    rtc_current_phase2:
      friendly_name: Real time consumtion phase 2
      unit_of_measurement: A
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase2") }}'
    rtc_current_phase3:
      friendly_name: Real time consumtion phase 3
      unit_of_measurement: A
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase3") }}'

    rtc_maxpower:
      friendly_name: Max power used
      unit_of_measurement: W
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "maxPower") }}'
    rtc_minpower:
      friendly_name: Min power used
      unit_of_measurement: W
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "minPower") }}'
    rtc_avgpower:
      friendly_name: Average power used
      unit_of_measurement: W
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "averagePower") }}'

    rtc_power_phase1:
      friendly_name: Real time consumtion phase 1
      unit_of_measurement: W
      value_template: >- 
        {% if state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase1") != "None" %}
        {% set w = (state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase1") | float) * (states("sensor.rtc_voltage") | float) %}
        {% else %}
        {% set w = 0 %}
        {% endif %}
        {{ w | round(2) }}
    rtc_power_phase2:
      friendly_name: Real time consumtion phase 2
      unit_of_measurement: W
      value_template: >- 
        {% if state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase2") != "None" %}
        {% set w = (state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase2") | float) * (states("sensor.rtc_voltage") | float) %}
        {% else %}
        {% set w = 0 %}
        {% endif %}
        {{ w | round(2) }}
    rtc_power_phase3:
      friendly_name: Real time consumtion phase 3
      unit_of_measurement: W
      value_template: >- 
        {% if state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase3") != "None" %}
        {% set w = (state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentPhase3") | float) * (states("sensor.rtc_voltage") | float) %}
        {% else %}
        {% set w = 0 %}
        {% endif %}
        {{ w | round(2) }}

    rtc_accumulated_consumption:
      friendly_name: Accumulated Consumption
      unit_of_measurement: kWh
      value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "accumulatedConsumption") }}'

- platform: integration
  source: sensor.real_time_consumption_johannedalsvagen_75_b
  name: energy_spent
  unit_prefix: k
  round: 2