- alias: "Turn on kitchen table light in the mornig if needed"
  id: 817ff13b-498f-46c2-aa7c-7f4017145ed1
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_34
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.everyone
        state: 'home'
      - condition: sun
        before: sunrise
      - condition: time
        after: '05:30'
        before: '08:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchentable


- alias: "Turn off some lights when leaving home"
  id: 18baae12-4d70-4341-9e32-ccc9a7fb90da
  trigger:
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.kitchentable
        - light.bedroom_ceiling
        - light.living_room
        - light.shelly_cinema_backrow
        - light.shelly_cinema_frontrow

- alias: "Light up the driveway when getting home"
  id: 93c8c1f8-2923-476a-9202-a13cd22e3742
  trigger:
    - platform: state
      entity_id: person.linus
      to: 'home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.garage_roof
      data:
        brightness: 255
    - delay: 180
    - service: light.turn_on
      entity_id: light.garage_roof
      data:
        brightness: 150