- alias: "Turn on kitchen table light in the mornig if needed"
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_34
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.everyone
        state: 'home'
      - condition: sun
        before: sunrise
      - condition: time
        after: '05:30'
        before: '08:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchentable


- alias: "Turn off some lights when leaving home"
  trigger:
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.kitchentable
        - light.bedroom_ceiling

- alias: "Light up the driveway when getting home"
  trigger:
    - platform: state
      entity_id: person.linus
      to: 'home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.garage_roof
      data:
        brightness: 255
    - delay: 180
    - service: light.turn_on
      entity_id: light.garage_roof
      data:
        brightness: 150