- alias: Bedroom remote bindings left
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control
      event: 4002
  action:
    service: light.turn_off
    entity_id:
      - light.ikea_e14_400lm

- alias: Bedroom remote bindings right
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control
      event: 5002
  action:
    service: light.turn_on
    entity_id:
      - light.ikea_e14_400lm
