- alias: 'Play SVT Morgonstudion on workdays'
  id: 0f78d2f7-45cb-4325-a57e-6413be373789
  trigger:
    platform: time
    at: "07:01:00"
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: svt_play.play_suggested
      entity_id: media_player.nesthub_kitchen
      data:
        program_name: morgonstudion
    - service: tv4_play.play_suggested
      entity_id: media_player.bedroom_tv
      data:
        program_name: nyhetsmorgon
