- alias: Kitchen remote bindings left
  id: eebbc061-1d7c-46c8-bf6d-1325eb6a9ce3
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control_kitchen
      event: 4002
  action:
    - service: svt_play.play_suggested
      entity_id: media_player.nesthub_kitchen
      data:
        program_name: morgonstudion

- alias: Kitchen remote bindings right
  id: 0948527f-0a2d-4c4b-a65c-950a105cc01c
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control_kitchen
      event: 5002
  action:
    - service: tv4_play.play_suggested
      entity_id: media_player.nesthub_kitchen
      data:
        program_name: nyhetsmorgon

- alias: Kitchen remote bindings right long
  id: d5f1205f-31e0-45c8-819b-7faee9a45c55
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control_kitchen
      event: 5001
  action:
    - service: media_player.turn_off
      entity_id: media_player.nesthub_kitchen
      

- alias: Kitchen remote bindings 1
  id: 724367bf-c504-4f5b-99c2-f2ec18ddd3b2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_onoff_test
      event: 1001
  action:
    service: light.toggle
    entity_id:
      - light.kitchen_sink

- alias: Kitchen remote bindings 0
  id: 8944bd2e-fe5c-4cb0-9e71-6a79d43ff42e
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_onoff_test
      event: 2001
  action:
    service: light.toggle
    entity_id:
      - light.kitchen_sink