- alias: "Legacy engine heater"
  initial_state: 'off'
  trigger:
    - platform: time
      at: '05:30'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.linus_trackers
        state: home
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_engine_heater

- alias: "Legacy engine heater off"
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: switch.switch_engine_heater
    to: 'on'
    for:
      hours: 2
  action:
    - service: switch.turn_off
      entity_id: switch.switch_engine_heater

