- alias: Livingroom remote bindings up
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch_livingroom
      event: 1001
  action:
    service: light.toggle
    entity_id:
      - light.living_room_lamps

- alias: Livingroom remote bindings down
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch_livingroom
      event: 2001
  action:
    service: light.toggle
    entity_id:
      - light.living_room_couch_lamp

- alias: TEST - Livingroom short up
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_onoff_test
      event: 1002
  action:
    - service: light.toggle
      entity_id:
        - light.liv_front_1
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_front_2
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_front_3
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_front_4
    - delay: 0.1

- alias: TEST - Livingroom short down
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_onoff_test
      event: 2002
  action:
    - service: light.toggle
      entity_id:
        - light.liv_back_1
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_back_2
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_back_3
    - delay: 0.1
    - service: light.toggle
      entity_id:
        - light.liv_back_4
    - delay: 0.1
  