- alias: "Garage movement: when not home"
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_16
      to: 'on'
  condition:
    condition: state
    entity_id: person.linus
    state: 'not_home'
  action:
    service: notify.pushbullet
    data:
      message: "Movement in the garage!"
      title: "ALERT"

- alias: "Garage movement: when dark"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_garage
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_garage_lightlevel
      below: 10
    - condition: state
      entity_id: sensor.garage_door_state
      state: 'Closed'
    - condition: state
      entity_id: sensor.garage_port_state
      state: 'Closed'
  action:
    service: notify.pushbullet
    data:
      message: "Probably an animal or insect in the garage"
      title: "ALERT"
