- alias: 'mqtt sensors: house_downstairs'
  id: b2b67d2e-9409-4e36-a633-d0db78ccea7f
  trigger:
    platform: state
    entity_id: sensor.cinema_temperature
  action:
    service: mqtt.publish
    data:
      topic: 'sensors/temperature/downstairs'
      payload: "{{ trigger.to_state.state }}"
      retain: true

- alias: 'mqtt sensors: house_upstairs'
  id: 177eee2c-06b2-4e65-9e78-419813893055
  trigger:
    platform: state
    entity_id: sensor.kitchen_temperature
  action:
    service: mqtt.publish
    data:
      topic: 'sensors/temperature/upstairs'
      payload: "{{ trigger.to_state.state }}"
      retain: true
    
- alias: 'mqtt sensors: cinema'
  id: 9ecaa2b7-dec2-48a5-8b13-7a09dddacb13
  trigger:
    platform: state
    entity_id: sensor.cinema_temperature
  action:
    service: mqtt.publish
    data:
      topic: 'sensors/temperature/cinema'
      payload: "{{ trigger.to_state.state }}"
      retain: true

