- alias: 'Sunset outdoor lights'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: group.outdoor_lights

- alias: 'Sunrise outdoor lights'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: group.outdoor_lights

