- alias: "tts test"
  initial_state: false
  trigger:
    platform: time
    at: "10:38"
  action:
  - service: tts.google_say
    entity_id:
      - media_player.bedroom_speaker
      - media_player.nesthub_kitchen
      - media_player.hobbyroom_speaker
    data_template:
      #entity_id: media_player.nesthub_kitchen
      message: "Kaffet är klart"
      language: sv

