- alias: 'Window lights sunset'
  id: 75470e48-9bd8-472f-b3f5-8834ff2d6833
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: time
    before: '23:30'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - group.window_lights
        - light.ikea_e14_400lm
        - light.guestroom_window_1

- alias: 'Window lights off at night'
  id: be207a50-3dce-478d-bf0e-14c5e2c941eb
  trigger:
    platform: time
    at: '23:30'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.window_lights
        - light.ikea_e14_400lm

- alias: 'Window lights sunrise'
  id: c073f007-09d7-4fc7-b749-3b39bbad60de
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: sun
    before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id: light.window_lights

- alias: 'Window lights off at sunrise'
  id: 03cc22b2-c269-4842-855a-0c28558a9886
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: time
    after: '06:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.window_lights
        - light.ikea_e14_400lm
        - light.guestroom_window_1

- alias: 'Window lights sunrise - bedroom'
  id: 1aac9f51-40b7-40b7-a337-ab6c12017e89
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: person.vi
        state: not_home
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.ikea_e14_400lm

- alias: 'Window lights sunrise - guestroom'
  id: f80c5d2b-a1f9-4ecb-86e9-53e437849ef0
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: group.visitors
        state: not_home
  action:
    - service: homeassistant.turn_on
      entity_id: light.guestroom_window_1
