- alias: 'Window lights sunset'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: time
    before: '23:30'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - group.window_lights
        - light.ikea_e14_400lm
        - light.guestroom_window_1

- alias: 'Window lights off at night'
  trigger:
    platform: time
    at: '23:30'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.window_lights
        - light.ikea_e14_400lm

- alias: 'Window lights sunrise'
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: sun
    before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id: light.window_lights

- alias: 'Window lights off at sunrise'
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: time
    after: '06:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.window_lights
        - light.ikea_e14_400lm
        - light.guestroom_window_1
- alias: 'Window lights sunrise - bedroom'
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: person.vi
        state: not_home
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.ikea_e14_400lm

- alias: 'Window lights sunrise - guestroom'
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: group.visitors
        state: not_home
  action:
    - service: homeassistant.turn_on
      entity_id: light.guestroom_window_1
