#homeassistant:
#  customize:
#    -
sensor:
  - platform: template
    sensors:
      catlocation:
        friendly_name: "Possible location"
        value_template: '{{ states.device_tracker.prick.state }}'
        icon_template: mdi:cat
group:
  people:
    name: Friends and family
    entities:
      - person.bjuhr
      - person.emma
      - person.farsan
      - person.kicki
      - person.klas
      - person.linus
      - person.martin
      - person.morsan
      - person.neonis
      - person.znike
      - person.bella

automation:
  - alias: "catdetector: bathroom"
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      to: 'on'
    condition:
      condition: state
      entity_id: group.people
      state: not_home
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'bathroom'

  - alias: "catdetector: closet"
    trigger:
      platform: state
      entity_id: binary_sensor.presence_21
      to: 'on'
    condition:
      condition: state
      entity_id: group.people
      state: not_home
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'closet'

  - alias: "catdetector: livingroom downstairs"
    trigger:
      platform: state
      entity_id: binary_sensor.presence_32
      to: 'on'
    condition:
      condition: state
      entity_id: group.people
      state: not_home
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'livingroom downstairs'

  - alias: "catdetector: hallway"
    trigger:
      platform: state
      entity_id: binary_sensor.presence_34
      to: 'on'
    condition:
      condition: state
      entity_id: group.people
      state: not_home
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'hallway'

  - alias: "catdetector: leaving house"
    trigger:
      platform: state
      entity_id: binary_sensor.pet_prick
      to: 'off'
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'outside'

  - alias: "catdetector: entering house"
    trigger:
      platform: state
      entity_id: binary_sensor.pet_prick
      to: 'on'
    action:
      - service: device_tracker.see
        data:
          dev_id: 'prick'
          location_name: 'inside'
