homeassistant:
  customize:
    sensor.rtc_voltage:
      grafana_name: "RTC voltage"
      friendly_name: "Real time consumtion voltage"
    sensor.rtc_power_phase1:
      grafana_name: "RTC power phase 1"
      friendly_name: "Real time consumtion phase 1"
    sensor.rtc_power_phase2:
      grafana_name: "RTC power phase 2"
      friendly_name: "Real time consumtion phase 2"
    sensor.rtc_power_phase3:
      grafana_name: "RTC power phase 3"
      friendly_name: "Real time consumtion phase 3"
    sensor.rtc_current_phase1:
      grafana_name: "RTC current phase 1"
      friendly_name: "Real time consumtion phase 1"
    sensor.rtc_current_phase2:
      grafana_name: "RTC current phase 2"
      friendly_name: "Real time consumtion phase 2"
    sensor.rtc_current_phase3:
      grafana_name: "RTC current phase 3"
      friendly_name: "Real time consumtion phase 3"
    sensor.rtc_accumulated_consumption:
      grafana_name: "RTC accumulated consumption"
      friendly_name: "Accumulated Consumption"
    sensor.rtc_avgpower:
      grafana_name: "RTC average power"
      friendly_name: "Average power used"
    sensor.rtc_power:
      grafana_name: "RTC power consumption"
      friendly_name: "Power consumption"

sensor:
  - platform: template
    sensors:
      rtc_voltage:
        unit_of_measurement: V
        value_template: >-
          {% set v = states('sensor.sp120_1_voltage') %}
          {% if v|round(0)|string|length != 3 %} {% set v = 230 %} {% endif %}
          {{ v }}

      # current reading for each phase
      # rtc_current_phase1_state:
      #   unit_of_measurement: A
      #   value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentL1") }}'    
      # rtc_current_phase2_state:
      #   unit_of_measurement: A
      #   value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentL2") }}'
      # rtc_current_phase3_state:
      #   unit_of_measurement: A
      #   value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "currentL3") }}'

      # power reading 
      rtc_avgpower_state:
        unit_of_measurement: W
        value_template: '{{ states("sensor.average_power_johannedalsvagen_75_b") }}'
        #value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "averagePower") }}'
      rtc_accumulated_consumption_state:
        unit_of_measurement: kWh
        value_template: '{{ states("sensor.accumulated_consumption_johannedalsvagen_75_b") }}'
        #value_template: '{{ state_attr("sensor.real_time_consumption_johannedalsvagen_75_b", "accumulatedConsumption") }}'

      # calculated power reading
      rtc_power_phase1:
        unit_of_measurement: W
        value_template: >- 
          {% set w = (states("sensor.rtc_current_phase1") | float) * (states("sensor.rtc_voltage") | float) %}
          {{ w | round(2) }}
      rtc_power_phase2:
        unit_of_measurement: W
        value_template: >- 
          {% set w = (states("sensor.rtc_current_phase2") | float) * (states("sensor.rtc_voltage") | float) %}
          {{ w | round(2) }}
      rtc_power_phase3:
        unit_of_measurement: W
        value_template: >- 
          {% set w = (states("sensor.rtc_current_phase3") | float) * (states("sensor.rtc_voltage") | float) %}
          {{ w | round(2) }}

  - platform: integration
    source: sensor.power_johannedalsvagen_75_b
    #source: sensor.real_time_consumption_johannedalsvagen_75_b
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: statistics
    entity_id: sensor.power_johannedalsvagen_75_b
    #entity_id: sensor.real_time_consumption_johannedalsvagen_75_b
    name: rtc_power_1min
    sampling_size: 40
    max_age:
      seconds: 30

  - platform: statistics
    entity_id: sensor.current_l1_johannedalsvagen_75_b
    name: rtc_current_phase1_1min
    sampling_size: 40
    max_age:
      seconds: 30
  
  - platform: statistics
    entity_id: sensor.current_l2_johannedalsvagen_75_b
    name: rtc_current_phase2_1min
    sampling_size: 40
    max_age:
      seconds: 30
  
  - platform: statistics
    entity_id: sensor.current_l3_johannedalsvagen_75_b
    name: rtc_current_phase3_1min
    sampling_size: 40
    max_age:
      seconds: 30

  - platform: statistics
    entity_id: sensor.rtc_avgpower_state
    name: rtc_avgpower_1min
    sampling_size: 10
    max_age:
      seconds: 30

  - platform: statistics
    entity_id: sensor.rtc_accumulated_consumption_state
    name: rtc_accumulated_consumption_1min
    sampling_size: 40
    max_age:
      seconds: 10

  # throttle sensors
  - platform: filter
    entity_id: sensor.rtc_power_1min
    name: "rtc_power"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"
  - platform: filter
    entity_id: sensor.rtc_accumulated_consumption_1min
    name: "rtc_accumulated_consumption"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"
  - platform: filter
    entity_id: sensor.rtc_avgpower_1min
    name: "rtc_avgpower"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"

  - platform: filter
    entity_id: sensor.rtc_current_phase1_1min
    name: "rtc_current_phase1"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"
  - platform: filter
    entity_id: sensor.rtc_current_phase2_1min
    name: "rtc_current_phase2"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"
  - platform: filter
    entity_id: sensor.rtc_current_phase3_1min
    name: "rtc_current_phase3"
    filters:
      - filter: time_throttle
        window_size: "00:00:10"
